import Navbar from './Navbar'
import Footer from './Footer'

export default function AboutPage({ onNavigate }) {
  return <><Navbar onNavigate={onNavigate} /><main>
    <section className="px-6 py-20 md:py-28 bg-gradient-to-br from-white via-white to-brand-50/70"><div className="max-w-5xl mx-auto grid md:grid-cols-[0.8fr_1.2fr] gap-12 items-center">
      <div className="mx-auto w-56 h-56 md:w-72 md:h-72 rounded-[2.5rem] overflow-hidden rotate-2 border-8 border-white shadow-[0_24px_60px_-24px_rgba(15,23,42,0.45)]"><img src="/profile.webp" alt="Luis Reyes Castro, psicólogo y desarrollador web en Talca" width="320" height="320" className="w-full h-full object-cover -rotate-2" /></div>
      <div><p className="text-sm font-semibold uppercase tracking-wider text-brand-600">Sobre Luis</p><h1 className="font-display text-4xl md:text-6xl font-extrabold tracking-tight text-slate-900 mt-4">Diseño webs pensando en las personas que deben decidir.</h1><p className="mt-6 text-lg text-slate-600 leading-relaxed">Soy Luis Reyes Castro, psicólogo y desarrollador web. Esa combinación me ayuda a trabajar la claridad, la confianza y el camino que sigue una persona antes de escribir, agendar o comprar.</p><a href="/diagnostico-web" onClick={(e) => { e.preventDefault(); onNavigate('/diagnostico-web') }} className="inline-flex mt-8 rounded-2xl bg-brand-600 px-6 py-3.5 text-white font-semibold">Cuéntame qué necesitas</a></div>
    </div></section>
    <section className="px-6 py-16 bg-white"><div className="max-w-5xl mx-auto grid md:grid-cols-3 gap-6"><div className="rounded-3xl border border-slate-100 bg-slate-50 p-6"><p className="text-brand-600 font-bold">01</p><h2 className="font-display text-xl font-bold mt-4 text-slate-900">Claridad antes que adorno</h2><p className="mt-3 text-slate-600 leading-relaxed">Primero ordenamos la oferta, el público y la acción que quieres que realice la visita.</p></div><div className="rounded-3xl border border-slate-100 bg-slate-50 p-6"><p className="text-brand-600 font-bold">02</p><h2 className="font-display text-xl font-bold mt-4 text-slate-900">Diseño con propósito</h2><p className="mt-3 text-slate-600 leading-relaxed">Cada sección debe responder una duda, demostrar algo o acercar el contacto.</p></div><div className="rounded-3xl border border-slate-100 bg-slate-50 p-6"><p className="text-brand-600 font-bold">03</p><h2 className="font-display text-xl font-bold mt-4 text-slate-900">Trabajo directo</h2><p className="mt-3 text-slate-600 leading-relaxed">Hablas conmigo durante el proceso, sin capas innecesarias entre tu negocio y quien construye la web.</p></div></div></section>
  </main><Footer onNavigate={onNavigate} /></>
}
